=== tewarid/course-xml/exemplos/topico-2/escola.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT escola (professores, estudantes, aulas)>
<!ATTLIST escola
	nome CDATA #REQUIRED
>
<!ELEMENT professores (professor+)>
<!ELEMENT professor EMPTY>
<!ATTLIST professor
	codigo ID #REQUIRED
	nome CDATA #REQUIRED
>
<!ELEMENT estudantes (estudante+)>
<!ELEMENT estudante EMPTY>
<!ATTLIST estudante
	codigo ID #REQUIRED
	nome CDATA #REQUIRED
>
<!ELEMENT aulas (aula+)>
<!ELEMENT aula (estudante_aula+)>
<!ATTLIST aula
	professor IDREF #REQUIRED
	materia (Matemática | Física | Química) #REQUIRED
>
<!ELEMENT estudante_aula EMPTY>
<!ATTLIST estudante_aula
	codigo IDREF #REQUIRED
>

=== tewarid/course-xml/exemplos/topico-2/escola.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE escola SYSTEM "escola.dtd">
<escola nome="São Joseph">
	<professores>
		<professor codigo="p1" nome="Alberto"/>
	</professores>
	<estudantes>
		<estudante codigo="e1" nome="Roberto"/>
		<estudante codigo="e2" nome="Larisa"/>
	</estudantes>
	<aulas>
		<aula professor="p1" materia="Matématica">
			<estudante_aula codigo="e1"/>
			<estudante_aula codigo="e2"/>
		</aula>
	</aulas>
</escola>
